# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "doink_left", "doink_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
# ---
include:
  - board: nice_nano_v2
    shield: pskeeb5_left
  - board: nice_nano_v2
    shield: pskeeb5_right
    snippet: studio-rpc-usb-uart
  - board: nice_nano_v2
    shield: pskeeb5_right
    snippet: studio-rpc-usb-uart
    artifact-name: pskeeb5_right_studio_probe-nice_nano_v2-zmk
    cmake-args: "-DKEYMAP_FILE=$base_dir/config/pskeeb5_studio_probe.keymap -DCONFIG_ZMK_STUDIO_TRANSPORT_BLE=n -DCONFIG_ZMK_STUDIO_RPC_RX_BUF_SIZE=128 -DCONFIG_ZMK_STUDIO_RPC_TX_BUF_SIZE=512 -DCONFIG_ZMK_STUDIO_RPC_THREAD_STACK_SIZE=6144 -DCONFIG_ZMK_BEHAVIOR_LOCAL_ID_TYPE_CRC16=y"
  - board: nice_nano_v2
    shield: settings_reset
# include:
#   - board: nice_nano_v2
#     shield: doink_left
#   - board: nice_nano_v2
#     shield: doink_right
#   - board: nice_nano_v2
#     shield: settings_reset
