manifest:
  remotes:
    - name: klesh
      url-base: https://github.com/klesh
  projects:
    - name: zmk
      remote: klesh
      revision: b2d37fb44958f28e2bb711b0ef12ea74b87d8bb0
      import: app/west.yml
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: klesh
      revision: main
  self:
    path: config
